name: Azure Static Web Apps CI/CD
on:
  push:
    branches:    
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet publish FlawlessDevelopment.Web/FlawlessDevelopment.Web.csproj --configuration Release --output ./publish
      - name: 'Deploy to Azure Static Web App'
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'FlawlessDevelopment.Web'
          output_location: 'FlawlessDevelopment.Web/wwwroot'